### ISSUE TITLE
Bug with the time type

### ISSUE THREAD

**Issue by BWGucio** [ZiLko/Custom_Labels#2]
The time type is invisible and visible only on the pause menu after saving an options + after saving, the size drops by 1%
![image](https://github.com/ZiLko/Custom_Labels/assets/99192838/52ae0266-e4ef-4ff3-ac57-30eae8267c5e)
![image](https://github.com/ZiLko/Custom_Labels/assets/99192838/2218434d-e572-4460-bea3-a57e1d47f7c2)

**Comment by Zilko** [comment]
i fix
